apiVersion: v2
name: synkora
description: A Helm chart for Synkora on Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - synkora
  - ai
  - llm
  - chatbot
home: https://github.com/getsynkora/synkora-ai
sources:
  - https://github.com/getsynkora/synkora-ai
maintainers:
  - name: Raju Mazumder
    email: rajuniit@gmail.com

dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "18.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
